import json

player_names = [
    "Iñaki Peña",
    "Marc ter Stegen",
    "Ronald Araujo",
    "Clément Lenglet",
    "Nélson Semedo",
    "Marc Bartra",
    "Sergiño Dest",
    "Iñigo Martínez",
    "Óscar Mingueza",
    "Lucas Digne",
    "Marcos Alonso",
    "Júnior Firpo",
    "Héctor Fort",
    "Martín Cáceres",
    "Héctor Bellerín",
    "Moussa Wagué",
    "Yerry Mina",
    "Sergi Domínguez",
    "Jean-Clair Todibo",
    "Juan Miranda",
    "Jeison Murillo",
    "Jofre Torrents",
    "Muniesa",
    "Chumi",
    "Marlon Santos",
    "Emerson Royal",
    "Carles Planas",
    "Borja López",
    "Sergi Gómez",
    "Jorge Cuenca",
    "Edgar Ié",
    "Patric",
    "Marc Cucurella",
    "Andrés Cuenca",
    "Chadi Riad",
    "Mika Mármol",
    "Sergi Roberto",
    "Ronaldinho",
    "Neymar",
    "Philippe Coutinho",
    "Arturo Vidal",
    "André Gomes",
    "Marc Casadó",
    "Arthur",
    "Denis Suárez",
    "Riqui Puig",
    "Ilkay Gündogan",
    "Carles Aleñá",
    "Franck Kessié",
    "Oriol Romeu",
    "Nico González",
    "Pablo Torre",
    "Ilaix Moriba",
    "Sergi Samper",
    "Gerard Gumbau",
    "Dro Fernández",
    "Álvaro Sanz",
    "Wilfrid Kaptoum",
    "Oriol Busquets",
    "Álex Collado",
    "Toni Fernández",
    "Tomás Marqués",
    "Àlex Carbonell",
    "Matheus Fernandes",
    "Jose Manuel Rueda",
    "Aleix Garrido",
    "Monchu",
    "Lionel Messi",
    "Luis Suárez",
    "Ferran Torres",
    "Robert Lewandowski",
    "Ousmane Dembélé",
    "Alexis Sánchez",
    "Ansu Fati",
    "Antoine Griezmann",
    "Martin Braithwaite",
    "Munir El Haddadi",
    "Marcus Rashford",
    "Memphis Depay",
    "João Félix",
    "Trincão",
    "Sandro Ramírez",
    "Pau Víctor",
    "Pierre-Emerick Aubameyang",
    "Malcom",
    "Adama Traoré",
    "Vitor Roque",
    "Abdessamad Ezzalzouli",
    "Carles Pérez",
    "Ferrán Jutglà",
    "Yusuf Demir",
    "Marc Guiu",
    "José Arnáiz",
    "Ángel Alarcon",
    "Ilias Akhomach",
    "Konrad de la Fuente",
    "Aitor Cantalapiedra",
    "Marc Cardona",
    "Dani Rodríguez",
    "Abel Ruiz",
    "Estanis Pedrola"
]

notifications = {
    "starting": True,
    "bench": True,
    "goal": True,
    "assist": True,
    "substitution": True,
    "yellow_card": True,
    "red_card": True,
    "rating": True,
    "transfer": True
}

players = []

for name in player_names:
    players.append({
        "name": name,
        "fotmob_id": None,
        "notifications": notifications.copy()
    })

with open("players.json", "w", encoding="utf-8") as file:
    json.dump(
        {"players": players},
        file,
        indent=4,
        ensure_ascii=False
    )

print(f"Created players.json with {len(players)} players.")
